### ISSUE TITLE
Integrate domain

### ISSUE THREAD

**Issue by yancyn** [hlgranite/hlgranite.github.io#2]

**Comment by hlgranite** [comment]
See help https://help.github.com/articles/adding-a-cname-file-to-your-repository/

**Comment by yancyn** [comment]
It takes one day for the CNAME to propagate. It is working without any problem now.

**Comment by yancyn** [comment]
www.hlgranite.com domain expired and failed to transfer to my namecheap.com account now. Will follow up...

**Comment by yancyn** [comment]
Moved to namecheap service now and has been configure correctly to github page with hlgranite.com domain.
